config/routes.rb
ChunChen::Application.routes.draw do
  get "admin" => "admin#index"

  controller :signup do
    get  "signup" => :new
    post "signup" => :create
  end

  controller :signin do
    get    "signin"  => :new
    post   "signin"  => :create
    delete "signout" => :destroy
  end

  root 'board#index'

  

end

app/models/user.rb
require "model_validators"

class User < ActiveRecord::Base

  validates :name,  presence: true, uniqueness: true
  validates :email, presence: true, email_format: true, uniqueness: true
  validates :password, length: { in: 6..20 }, password_format: true

  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authorize

  def authorize
    if session[:user_id]
      redirect_to admin_url
    end
  end

  def new
  end

  def create
    if !(user = User.find_by_name(params[:name]))
      alert = "User doesn't exist"
    elsif !user.authenticate(params[:password])
      alert = "Password is invalid"
    end

    unless alert
      session[:user_id] = user.id
      redirect_to admin_url
    else
      redirect_to login_url, :alert => alert
    end
  end

  def destroy
    session[:user_id] = nil
  end
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  before_filter :has_signed_in, only: [:new, :create]

  def has_signed_in
    if session[:user_id]
      redirect_to root_url
    end
  end

  def new
  end

  def create
    if !(user = User.find_by_name(params[:name]))
      alert = "User doesn't exist"
    elsif !user.authenticate(params[:password])
      alert = "Password is invalid"
    end

    unless alert
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now[:alert] = alert

      # Clear input password
      params[:password] = nil
      render :new
    end
  end

  def destroy
    unless session[:user_id]
      flash.now[:alert] = "You need to sign in, first"
      render :new
    else
      session[:user_id] = nil
      redirect_to root_url
    end
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  before_filter :has_signed_in

  def has_signed_in
    if session[:user_id]
      redirect_to root_url
    end
  end

  # GET /signup/new
  def new
    @user = User.new
  end

  # POST /signup
  def create
    @user = User.new(input_params)

    if @user.save
      # Recode user id in session
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'User was successfully created'
    else
      render :new
    end
  end

private
  # Never trust parameters from the scary internet, only allow the white list through.
  def input_params
    params.require(:signup).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:index]

  def authorize
    unless session[:user_id]
      redirect_to login_url
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def has_user_signed?
    return (session[:user_id] != nil)
  end
end

app/helpers/board_helper.rb
module BoardHelper

  # Give the name of signed user  
  def signed_name
    if has_user_signed?
      User.find_by_id(session[:user_id]).name
    else
      "buddy"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/signup_helper.rb
module SignupHelper

  def mark_necessary_field(obj, attr)
    "*" if obj.class.validators_on(attr).map(&:class).flatten.include?(
        ActiveRecord::Validations::PresenceValidator)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/board/index.html.erb
<% unless has_user_signed? %>
  <%= link_to "Sign Up", signup_path %>
  <%= link_to "Sign In", signin_path %>
<% else %>
  <%= link_to "Sign Out", signout_path, method: "delete" %>
<% end %>

<h1>Plan Board</h1>
<p>Welcome, <B><%= signed_name %></B>!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChunChen</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/signin/create.html.erb
<h1>Signin#create</h1>
<p>Find me in app/views/signin/create.html.erb</p>

app/views/signin/destroy.html.erb
<h1>Signin#destroy</h1>
<p>Find me in app/views/signin/destroy.html.erb</p>

app/views/signin/new.html.erb
<div class="depot_form" >
  <% if alert %>
    <p id="notice" ><%= alert %></p>
  <% end %>

  <fieldset>
    <legend>Please Sign In</legend>

    <%= form_tag do %>
    <table>
      <tr class="field">
        <td><label for="name" >Name:</label></td>
        <td><%= text_field_tag :name, params[:name], size: 24 %></td>
      </tr>
      <tr class="field">
        <td><label for="password" >Password:</label></td>
        <td><%= password_field_tag :password, params[:password], size: 25 %></td>
      </tr>
      <tr class="actions">
        <td><%= submit_tag "Sign In" %></td>
      </tr>
    </table>
    <% end %>

  </fieldset>
</div>

app/views/signup/new.html.erb
<h1>New user</h1>

<%= form_for(@user, as: :signup, url: signup_path) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %> <%= mark_necessary_field(@user, :name) %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %> <%= mark_necessary_field(@user, :email) %><br>
    <%= f.text_field :email, placeholder: "Email addr" %>
  </div>
  <div class="field">
    <%= f.label :password %> <%= mark_necessary_field(@user, :password) %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label "Confirm Password"%> <%= mark_necessary_field(@user, :password_confirmation) %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label "Confirm Password"%><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password digest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>